bar:
  height: 38
  location: top
  background: 0d1218ff
  foreground: e5e9f0ff
  font: JetBrains Mono:size=14
  # https://www.mankier.com/5/yambar-modules-battery
  left:
    - i3:
        # for colors and lines see this link
        # https://codeberg.org/dnkl/yambar/src/branch/master/doc/yambar-decorations.5.scd
        strip-workspace-numbers: true
        sort: ascending
        content:
          "1:":
            map:
              default:
                string:
                  text: "{name}"
                  margin: 12
                  foreground: 6d87a0ff
                  #on-click: "swaymsg --quiet workspace 1:{name}"
                  on-click: "swaymsg --quiet workspace 1:{name}"
                  deco: {background: {color: 171717ff}}
              conditions:
                state == focused: {string: {text: "{name}", font: "JetBrains Mono:weight=170:size=16", margin: 12}}
          "2:":
            map:
              default:
                string:
                  text: "{name}"
                  margin: 12
                  foreground: 6d87a0ff
                  #on-click: "swaymsg --quiet workspace 1:{name}"
                  on-click: "swaymsg --quiet workspace 2:{name}"
                  deco: {background: {color: 171717ff}}
              conditions:
                state == focused: {string: {text: "{name}", font: "JetBrains Mono:weight=170:size=16", margin: 12}}
          "3:":
            map:
              default:
                string:
                  text: "{name}"
                  margin: 12
                  foreground: 6d87a0ff
                  #on-click: "swaymsg --quiet workspace 1:{name}"
                  on-click: "swaymsg --quiet workspace 3:{name}"
                  deco: {background: {color: 171717ff}}
              conditions:
                state == focused: {string: {text: "{name}", font: "JetBrains Mono:weight=170:size=16", margin: 12}}
          "4:":
            map:
              default:
                string:
                  text: "{name}"
                  margin: 12
                  foreground: 6d87a0ff
                  #on-click: "swaymsg --quiet workspace 1:{name}"
                  on-click: "swaymsg --quiet workspace 4:{name}"
                  deco: {background: {color: 171717ff}}
              conditions:
                state == focused: {string: {text: "{name}", font: "JetBrains Mono:weight=170:size=16", margin: 12}}
          "5:":
            map:
              default:
                string:
                  text: "{name}"
                  margin: 12
                  foreground: 6d87a0ff
                  #on-click: "swaymsg --quiet workspace 1:{name}"
                  on-click: "swaymsg --quiet workspace 5:{name}"
                  deco: {background: {color: 171717ff}}
              conditions:
                state == focused: {string: {text: "{name}", font: "JetBrains Mono:weight=170:size=16", margin: 12}}
          "6:":
            map:
              default:
                string:
                  text: "{name}"
                  margin: 12
                  foreground: 6d87a0ff
                  #on-click: "swaymsg --quiet workspace 1:{name}"
                  on-click: "swaymsg --quiet workspace 6:{name}"
                  deco: {background: {color: 171717ff}}
              conditions:
                state == focused: {string: {text: "{name}", font: "JetBrains Mono:weight=170:size=16", margin: 12}}
          "7:":
            map:
              default:
                string:
                  text: "{name}"
                  margin: 12
                  foreground: 6d87a0ff
                  #on-click: "swaymsg --quiet workspace 1:{name}"
                  on-click: "swaymsg --quiet workspace 7:{name}"
                  deco: {background: {color: 171717ff}}
              conditions:
                state == focused: {string: {text: "{name}", font: "JetBrains Mono:weight=170:size=16", margin: 12}}
          "8:":
            map:
              default:
                string:
                  text: "{name}"
                  margin: 12
                  foreground: 6d87a0ff
                  #on-click: "swaymsg --quiet workspace 1:{name}"
                  on-click: "swaymsg --quiet workspace 8:{name}"
                  deco: {background: {color: 171717ff}}
              conditions:
                state == focused: {string: {text: "{name}", font: "JetBrains Mono:weight=170:size=16", margin: 12}}
          "9:":
            map:
              default:
                string:
                  text: "{name}"
                  margin: 12
                  foreground: 6d87a0ff
                  #on-click: "swaymsg --quiet workspace 1:{name}"
                  on-click: "swaymsg --quiet workspace 9:{name}"
                  deco: {background: {color: 171717ff}}
              conditions:
                state == focused: {string: {text: "{name}", font: "JetBrains Mono:weight=170:size=16", margin: 12}}
          "10:":
            map:
              default:
                string:
                  text: "{name}"
                  margin: 12
                  foreground: 6d87a0ff
                  #on-click: "swaymsg --quiet workspace 1:{name}"
                  on-click: "swaymsg --quiet workspace 10:{name}"
                  deco: {background: {color: 171717ff}}
              conditions:
                state == focused: {string: {text: "{name}", font: "JetBrains Mono:weight=170:size=16", margin: 12}}
          "":
            map:
              default:
                string:
                  text: "{name}"
                  margin: 12
                  foreground: 6d87a0ff
                  #on-click: "swaymsg --quiet workspace 1:{name}"
                  on-click: "swaymsg --quiet workspace {name}"
                  deco: {background: {color: 171717ff}}
              conditions:
                state == focused: {string: {text: "{name}", font: "JetBrains Mono:weight=170:size=16", margin: 12}}
          current: {string: {text: "{title}", left-margin: 12, max: 44}}
  right:
    - battery:
        name: BAT0
        poll-interval: 30000
        content:
          - string:
              text: "Battery"
              margin: 12
              foreground: 6d87a0ff
              deco: {background: {color: 171717ff}}
          - string: {text: "{capacity}%", font: "JetBrains Mono:weight=170:size=16", left-margin: 12, right-margin: 32}
    - network:
        poll-interval: 20000
        content:
          map:
            default: {empty: {}}
            conditions:
              name == wlp4s0:
                map:
                  default: {string: {text: "", font: "JetBrains Mono:weight=170:size=16", margin: 12, foreground: 6d87a0ff, deco: {background: {color: 171717ff}}}}
                  conditions:
                    state == down: {string: {text: "", font: "JetBrains Mono:weight=170:size=16", foreground: ff0000ff}}
                    state == up:
                      map:
                        default:
                          - string: {text: "", font: "JetBrains Mono:weight=170:size=16", margin: 12, foreground: 6d87a0ff, deco: {background: {color: 171717ff}}}
                          - string: {text: "{dl-speed} {ssid}", font: "JetBrains Mono:weight=170:size=16", left-margin: 12, right-margin: 12}

                        conditions:
                          ipv4 == "":
                            - string: {text: "", font: "JetBrains Mono:weight=170:size=16", margin: 12, foreground: 6d87a0ff, deco: {background: {color: 171717ff}}}
                            - string: {text: "{dl-speed} {ssid}", font: "JetBrains Mono:weight=170:size=16", foreground: ffffff66, left-margin: 12, right-margin: 12}
    - pipewire:
        anchors:
          volume: &volume
            conditions:
              muted: {string: {text: "*{cubic_volume}%*", foreground: ff0000ff}}
              ~muted: {string: {text: "~{cubic_volume}%~"}}
        content:
          list:
            items:
              - map:
                  conditions:
                    type == "sink":
                      map:
                        conditions:
                          icon == "audio-headset-bluetooth":
                            string: {text: " 🎧 "}
                          muted:
                            - string:
                                text: "Audio"
                                margin: 12
                                foreground: 6d87a0ff
                                deco: {background: {color: 171717ff}}
                            - string:
                                on-click:
                                  left: "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
                                  wheel-up: "wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+ --limit 1.0"
                                  wheel-down: "wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-"
                                text: "{cubic_volume}%"
                                foreground: 7ecfd4ff
                                font: "JetBrains Mono:weight=170:size=16"
                                margin: 12
                        default:
                          - string:
                              text: "Audio"
                              margin: 12
                              foreground: 6d87a0ff
                              deco: {background: {color: 171717ff}}
                          - string:
                              on-click:
                                left: "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
                                wheel-up: "wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+ --limit 1.0"
                                wheel-down: "wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-"
                              text: "{cubic_volume}%"
                              font: "JetBrains Mono:weight=170:size=16"
                              margin: 12
                  <<: *volume
  center:
    - clock:
        time-format: "%H:%M"
        date-format: "%B %d, %a"
        content:
          - string: {text: "{date}", font: "JetBrains Mono:weight=170:size=16", right-margin: 8}
          - string: {text: "{time}", font: "JetBrains Mono:weight=170:size=16"}